#tomcat启动端口
server:
  port: 8888
#Rabbitmq的配置
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: geust
    password: geust

## 畹町贸易数据接口
#spring:
#  rabbitmq:
#    host: 116.52.77.162
#    port: 35672
#    virtual-host: shengshi
#    username: shengshi
#    password: shengshi123
