server:
  port: 8000
spring:
  application:
    name: sharding-jdbc-spring-boot
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/database0?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
        username: root
        password: '123456'
        hikari:
          minimum-idle: 5
          idle-timeout: 600000
          maximum-pool-size: 10
          auto-commit: true
          pool-name: MyHikariCP
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/database1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
        username: root
        password: '123456'
        hikari:
          minimum-idle: 5
          idle-timeout: 600000
          maximum-pool-size: 10
          auto-commit: true
          pool-name: MyHikariCP
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1
#      ds2:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3306/database2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong&useSSL=false
#        username: root
#        password: '123456'
#        hikari:
#          minimum-idle: 5
#          idle-timeout: 600000
#          maximum-pool-size: 10
#          auto-commit: true
#          pool-name: MyHikariCP
#          max-lifetime: 1800000
#          connection-timeout: 30000
#          connection-test-query: SELECT 1
    sharding:
      binding-tables: tb_order
      default-database-strategy:
        inline:
          algorithm-expression: ds$->{user_id % 2}
          sharding-column: user_id
      tables:
        tb_order:
          actual-data-nodes: ds$->{0..1}.tb_order_$->{0..1}
          table-strategy:
            inline:
              algorithm-expression: tb_order_$->{order_id % 2}
              sharding-column: order_id
#        tb_order_item:
#          actual-data-nodes: ds$->{0..1}.tb_order_item_$->{0..1}
#          table-strategy:
#            inline:
#              algorithm-expression: tb_order_item_$->{order_id % 2}
#              sharding-column: order_id

mybatis-plus:
  global-config:
    banner: false
mybatis:
  type-aliases-package: com.lianekai.sharding.pojo
  mapper-locations: classpath:mapper/*.xml
